Repository grails/grails-views, pull requests merged in 2024-03, with the labels that each got.

#553 chore(releasenotes): udpate workflow configurations
  .github/workflows/release-notes.yml
Labels: maintenance, chore

#559 fix(release): Set the correct artifactId
  gradle/publishing.gradle
Labels: bug

#561 fix(deps): Set correct dependency configurations
  core/build.gradle
  core/src/main/groovy/grails/views/mvc/renderer/DefaultViewRenderer.groovy
  gradle-plugin/build.gradle
  gradle-plugin/src/main/groovy/grails/views/gradle/markup/GrailsMarkupViewsPlugin.groovy
  gradle/libs.versions.toml
  json-templates/build.gradle
  json-testing-support/build.gradle
  json/build.gradle
  markup/build.gradle
  markup/src/main/groovy/grails/plugin/markup/view/MarkupViewGrailsPlugin.groovy
  markup/src/main/groovy/grails/plugin/markup/view/MarkupViewTemplate.groovy
  markup/src/main/groovy/grails/plugin/markup/view/MarkupViewTemplateEngine.groovy
  markup/src/main/groovy/grails/plugin/markup/view/mvc/MarkupViewResolver.groovy
Labels: bug, maintenance, deps

#565 chore(releasenotes): update workflow configurations
  .github/release-drafter.yml
Labels: maintenance, chore
